version: '3'

services:
  redis:
    image: 'redis:alpine'

  web:
    build: .
    command: 'flask run --host=0.0.0.0 -p 5000'
    environment:
      PYTHONUNBUFFERED: 'true'
      FLASK_APP: 'app.py'
      SECRET_KEY: 'sample_secret_key'
      FLASK_DEBUG: 1
      SEI_ID: 'sample_sei_id'
      SEI_SECRET: 'sample_sei_secret'
    volumes:
      - '.:/app'
    ports:
      - '5000:5000'
