service: hpe-connector
# app and org for use with dashboard.serverless.com
app: hpe-connector
org: natfoster

custom:
  pythonRequirements:
    dockerizePip: true
  SEI_URL_BASE:
    dev: https://sei-stage.herokuapp.com
    stage: ${secrets:SEI_URL_BASE}
    prod: ${secrets:SEI_URL_BASE}
  PSI_URL_BASE:
    dev: https://apiuatapi.psiexams.com
    stage: ${secrets:PSI_URL_BASE}
    prod: ${secrets:PSI_URL_BASE}
  SLACK_WEBHOOK_URL:
    dev: ${secrets:SLACK_WEBHOOK_URL}
    stage: ${secrets:SLACK_WEBHOOK_URL}
    prod: ${secrets:SLACK_WEBHOOK_URL}
  SLACK_CHANNEL:
    dev: ${secrets:SLACK_CHANNEL}
    stage: ${secrets:SLACK_CHANNEL}
    prod: ${secrets:SLACK_CHANNEL}
  PSI_PASSWORD:
    dev: ${secrets:PSI_PASSWORD}
    stage: ${secrets:PSI_PASSWORD}
    prod: ${secrets:PSI_PASSWORD}
  PSI_CONSUMER_KEY:
    dev: ${secrets:PSI_CONSUMER_KEY}
    stage: ${secrets:PSI_CONSUMER_KEY}
    prod: ${secrets:PSI_CONSUMER_KEY}
  PSI_CONSUMER_SECRET:
    dev: ${secrets:PSI_CONSUMER_SECRET}
    stage: ${secrets:PSI_CONSUMER_SECRET}
    prod: ${secrets:PSI_CONSUMER_SECRET}

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage,'dev'}
  environment:
    STAGE: ${opt:stage,'dev'}
    SEI_URL_BASE: ${self:custom.SEI_URL_BASE.${self:provider.stage}}
    PSI_URL_BASE: ${self:custom.PSI_URL_BASE.${self:provider.stage}}
    SLACK_WEBHOOK_URL: ${self:custom.SLACK_WEBHOOK_URL.${self:provider.stage}}
    SLACK_CHANNEL: ${self:custom.SLACK_CHANNEL.${self:provider.stage}}
    PSI_PASSWORD: ${self:custom.PSI_PASSWORD.${self:provider.stage}}
    PSI_CONSUMER_KEY: ${self:custom.PSI_CONSUMER_KEY.${self:provider.stage}}
    PSI_CONSUMER_SECRET: ${self:custom.PSI_CONSUMER_SECRET.${self:provider.stage}}

functions:
  handle_sei_event:
    handler: handler.handle_sei_event
  handle_delivery_widget:
    handler: handler.handle_delivery_widget

plugins:
  - serverless-python-requirements
