version: '3'

services:
  redis:
    image: 'redis:alpine'

  web:
    build: .
    command: 'flask run --host=0.0.0.0 -p 5000'
    env_file:
      - '.env'
    volumes:
      - '.:/app'
    ports:
      - '5000:5000'

  scheduler:
    build: .
    command: 'python scheduler.py'
    env_file:
      - '.env'
    volumes:
      - '.:/app'

  worker:
    build: .
    command: 'python worker.py'
    env_file:
      - '.env'
    volumes:
      - '.:/app'